# Generated by Django 5.2.13 on 2026-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='kilos_per_basket',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How many kilos one basket represents for this supplier and product.', max_digits=10, null=True),
        ),
    ]
