# Generated by Django 5.2.13 on 2026-04-08 21:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_supplierproduct_kilos_per_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='total_kilos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
