# Generated by Django 5.2.13 on 2026-04-08 21:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_purchaseinvoice_total_kilos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='basket_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='kilos_per_basket',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='supplier_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.supplierproduct'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='total_kilos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per kg according to the selected supplier product.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Real weight if entered manually.', max_digits=12, null=True),
        ),
    ]
