# Generated by Django 5.2.13 on 2026-04-08 21:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_purchaseinvoiceitem_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items_legacy', to='core.product'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='default_purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default purchase price for this supplier and product.', max_digits=12),
        ),
    ]
