# Generated by Django 5.2.13 on 2026-04-08 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchaseinvoiceitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='supplier_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.supplierproduct'),
        ),
    ]
