# Generated by Django 5.2.13 on 2026-04-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_purchaseinvoiceitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
