# Generated by Django 5.2.13 on 2026-04-09 00:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customer_neighborhood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-invoice_date', '-id'], 'verbose_name': 'Factura de venta', 'verbose_name_plural': 'Facturas de venta'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceitem',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de factura de venta', 'verbose_name_plural': 'Detalles de factura de venta'},
        ),
        migrations.AlterModelOptions(
            name='salespayment',
            options={'ordering': ['-payment_date', '-id'], 'verbose_name': 'Pago de venta', 'verbose_name_plural': 'Pagos de venta'},
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor pagado'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Saldo pendiente'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='El número de factura debe tener exactamente 4 dígitos.', regex='^\\d{4}$')], verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Abonada'), ('paid', 'Pagada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total factura'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='blocks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bloques'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesinvoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='core.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio por kilo o por bloque según el tipo de venta del producto.', max_digits=12, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor pagado'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.salesinvoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago'),
        ),
    ]
