# Generated by Django 5.2.13 on 2026-04-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kg_per_block',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso promedio de un bloque en kg. Se usa para calcular bloques automáticamente.', max_digits=6, null=True, verbose_name='Kg por bloque'),
        ),
    ]
