# Generated by Django 5.2.13 on 2026-04-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_kg_per_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Mensajero',
                'verbose_name_plural': 'Mensajeros',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='mensajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='core.mensajero', verbose_name='Mensajero'),
        ),
    ]
