# Generated by Django 5.2.13 on 2026-04-21 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre / Referencia')),
                ('plate', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fuel', 'Gasolina'), ('utilities', 'Servicios públicos'), ('rent', 'Arriendo'), ('payroll', 'Nómina'), ('administrative', 'Gastos administrativos'), ('supplies', 'Insumos (bolsas, facturas, etc.)'), ('uniform', 'Dotación'), ('other', 'Otro')], max_length=30, verbose_name='Categoría')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('motorcycle', models.ForeignKey(blank=True, help_text='Solo para gastos de gasolina.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.motorcycle', verbose_name='Moto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
