# Generated by Django 5.2.13 on 2026-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_motorcycle_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='block_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Bloques reales recibidos en esta compra. Se usa para el inventario.', null=True, verbose_name='Cantidad de bloques'),
        ),
    ]
