# Generated by Django 5.2.13 on 2026-05-27 16:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_purchaseinvoiceitem_block_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='NIT / Documento')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor de gastos',
                'verbose_name_plural': 'Proveedores de gastos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='applies_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica IVA (19%)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor IVA'),
        ),
        migrations.AddField(
            model_name='expense',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor base (sin IVA)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expenseprovider', verbose_name='Proveedor'),
        ),
    ]
